# 管理潜质测评配置文件
paper_id: 1
paper_name: "管理潜质测评"
paper_description: "管理潜质，代表了在更重要或更具有挑战的领导角色上有高绩效表现的发展可能性，是个体在管理序列上发展的动力和适应未来管理职位中复杂人际和事务的个性特点。"
paper_version: "v1.0"

# 数据字段映射（Excel列名到内部字段名的映射）
field_mapping:
  姓名: "name"
  总分: "total_score"
  大维度1：自我成长与发展: "自我成长与发展"
  小维度1：学习与探索动机: "学习与探索动机"
  小维度2：寻求和运用反馈: "寻求和运用反馈"
  小维度3：情感成熟度: "情感成熟度"
  大维度2：管理动力: "管理动力"
  小维度4：领导意愿: "领导意愿"
  小维度5：追求成就: "追求成就"
  小维度6：组织意识: "组织意识"
  大维度3：管理他人: "管理他人"
  小维度7：人际洞察: "人际洞察"
  小维度8：同理心: "同理心"
  小维度9：发挥他人: "发挥他人"
  大维度4：管理事务: "管理事务"
  小维度10：跨领域思考: "跨领域思考"
  小维度11：概念性思维: "概念性思维"
  小维度12：适应变化情境: "适应变化情境"

# 维度结构定义
dimensions:
  - name: "自我成长与发展"
    color: "#00CC00"
    description: "展现个人成长内驱力和发展潜力"
    radar_angles: [0, 30, 60]
    sub_dimensions:
      - name: "学习与探索动机"
        description: "主动学习新知识和探索未知领域的动机"
      - name: "寻求和运用反馈"
        description: "主动获取反馈并将其转化为成长动力的能力"
      - name: "情感成熟度"
        description: "在压力情境中保持情绪稳定和理性的能力"

  - name: "管理动力"
    color: "#9900FF"
    description: "驱动个人在管理岗位上发展的内在动力"
    radar_angles: [90, 120, 150]
    sub_dimensions:
      - name: "领导意愿"
        description: "承担领导责任和引领团队的意愿"
      - name: "追求成就"
        description: "追求卓越绩效和持续改进的动力"
      - name: "组织意识"
        description: "理解组织运作机制和战略方向的能力"

  - name: "管理他人"
    color: "#FF3333"
    description: "在复杂人际环境中有效管理和影响他人的能力"
    radar_angles: [270, 300, 330]
    sub_dimensions:
      - name: "人际洞察"
        description: "敏锐感知他人情感和动机的能力"
      - name: "同理心"
        description: "理解他人立场和感受的能力"
      - name: "发挥他人"
        description: "识别和培养他人潜力的能力"

  - name: "管理事务"
    color: "#0066FF"
    description: "处理复杂业务问题和系统思考的能力"
    radar_angles: [180, 210, 240]
    sub_dimensions:
      - name: "跨领域思考"
        description: "整合不同领域知识和思维模式的能力"
      - name: "概念性思维"
        description: "抽象思维和系统分析的能力"
      - name: "适应变化情境"
        description: "在变化环境中保持灵活性和适应性的能力"

# 分数区间定义
score_levels:
  - name: "高潜力"
    min: 8.5
    max: 10.0
    summary: "说明其具有卓越的领导潜质，在领导力通道上具备快速晋升的强劲潜力。这类人才不仅能在更高层级的领导角色上持续创造卓越绩效，且有潜力在战略层面引领组织变革与发展。"
    development_focus: "需着重培养其战略领导力与跨体系协同能力，同时防范长期高压环境下的倦怠风险"
    color: "#4CAF50"

  - name: "中高潜力"
    min: 7.5
    max: 8.4
    summary: "说明其具备可培养的领导潜质基础，经过系统化训练可能在2-3年内胜任更高层级的领导角色。在匹配其优势领域的管理岗位上具备产出高绩效的潜力，但需强化关键能力的突破性成长。"
    development_focus: "应制定针对性发展计划，重点补足跨维度能力短板"
    color: "#FFC107"

  - name: "中等潜力"
    min: 6.5
    max: 7.4
    summary: "具备基础管理潜质但需要系统化培养。在特定管理岗位上可能表现稳定，但晋升潜力有限，需要针对性强化关键能力短板。"
    development_focus: "重点提升核心管理能力，建立系统化发展路径"
    color: "#3498db"

  - name: "基础潜力"
    min: 1.0
    max: 6.4
    summary: "管理潜质基础薄弱，需要长期培养和大量实践。建议在专业岗位上深耕，或通过专项培训提升管理意识。"
    development_focus: "建议在专业岗位发展，或通过专项培训提升管理意识"
    color: "#F44336"

# 维度评价内容
dimension_evaluations:
  自我成长与发展:
    high:
      dimension_eval: "展现出卓越的成长内驱力，系统化构建个人发展路径。能够精准把握学习机会，成熟运用反馈机制实现持续迭代，在压力情境中保持情绪韧性，形成自我成长的良性循环。"
      sub_dimensions:
        学习与探索动机:
          潜质特点: "具备强烈的好奇心和认知拓展热情，主动挑战能力舒适区。将陌生领域视为成长契机，持续构建跨领域知识体系"
          工作中的倾向: "在日常工作中创造学习机会，主动承担未知领域的任务；建立行业信息网络，将新知识快速转化为实践能力"
        寻求和运用反馈:
          潜质特点: "建立常态化反馈获取机制，将批评意见转化为成长燃料。能识别不同来源反馈的价值差异，选择性融合多维信息"
          工作中的倾向: "周期性主动寻求360度反馈；建立反馈转化日志，在关键决策前专门征求反对意见；推动团队形成反馈文化"
        情感成熟度:
          潜质特点: "在高强度压力下保持决策理性，将挫折转化为成长养分。具备情绪预警机制，在情绪波动前主动调节"
          工作中的倾向: "面对项目失败时引领团队复盘学习；在高风险决策中保持理性客观；建立个人情绪恢复仪式"

    medium:
      dimension_eval: "具备基础成长意识但缺乏系统规划。在熟悉领域学习主动性强，但面对未知领域存在畏惧；能接受直接反馈但转化效率不足；情绪管理呈阶段性波动。"
      sub_dimensions:
        学习与探索动机:
          潜质特点: "在擅长领域保持学习热情，但对能力短板领域回避探索。学习驱动力受外部目标牵引强于内在好奇"
          工作中的倾向: "愿意参与公司组织的培训，但较少自发拓展；面对新任务时需要明确指导而非自主探索"
        寻求和运用反馈:
          潜质特点: "能接受上级直接反馈但回避同级评价。对建设性意见需要消化时间，偶尔出现选择性接受"
          工作中的倾向: "考核期会主动寻求反馈但缺乏连续性；能够参照明确建议改进工作，但难以转化模糊意见"
        情感成熟度:
          潜质特点: "普通压力下表现稳定，但重大挫折时情绪恢复期较长。能意识到情绪变化但调节手段单一"
          工作中的倾向: "常规工作压力下保持正常状态；项目受挫时需2-3天恢复期；面对连续挫折可能出现判断偏差"

    low:
      dimension_eval: "成长主动性薄弱，反馈回避倾向明显。学习局限于岗位必需技能，对反馈持防御心态，情绪波动显著影响工作表现。"
      sub_dimensions:
        学习与探索动机:
          潜质特点: "存在明显学习舒适区，对新领域产生本能排斥。将能力短板视为不可变因素"
          工作中的倾向: "拒绝跨职能任务机会；沿用固定工作方法；知识更新滞后岗位要求"
        寻求和运用反馈:
          潜质特点: "将反馈视为负面评价，产生自我辩护机制。建设性意见常触发抵触情绪"
          工作中的倾向: "对反馈建议解释为认知差异；改进措施流于表面；重要决策回避征求他人意见"
        情感成熟度:
          潜质特点: "情绪调节能力薄弱，挫折后易陷入消极循环。将工作困难归因为外部因素"
          工作中的倾向: "压力下出现决策瘫痪；项目受挫后影响后续任务表现；情绪波动传染团队氛围"

    bad:
      dimension_eval: "成长主动性薄弱，反馈回避倾向明显。学习局限于岗位必需技能，对反馈持防御心态，情绪波动显著影响工作表现。"
      sub_dimensions:
        学习与探索动机:
          潜质特点: "存在明显学习舒适区，对新领域产生本能排斥。将能力短板视为不可变因素"
          工作中的倾向: "拒绝跨职能任务机会；沿用固定工作方法；知识更新滞后岗位要求"
        寻求和运用反馈:
          潜质特点: "将反馈视为负面评价，产生自我辩护机制。建设性意见常触发抵触情绪"
          工作中的倾向: "对反馈建议解释为认知差异；改进措施流于表面；重要决策回避征求他人意见"
        情感成熟度:
          潜质特点: "情绪调节能力薄弱，挫折后易陷入消极循环。将工作困难归因为外部因素"
          工作中的倾向: "压力下出现决策瘫痪；项目受挫后影响后续任务表现；情绪波动传染团队氛围"

  管理动力:
    high:
      dimension_eval: "展现出强烈的管理内驱力和卓越的领导意愿。具备清晰的职业发展愿景，主动承担管理责任，在追求个人成就的同时推动组织发展。"
      sub_dimensions:
        领导意愿:
          潜质特点: "主动寻求领导机会，乐于承担团队责任。具备清晰的领导愿景和使命感"
          工作中的倾向: "主动承担项目负责人角色；在团队中发挥引领作用；积极推动组织变革"
        追求成就:
          潜质特点: "设定高目标并持续追求卓越。将挑战视为成长机会，具备强烈的成就动机"
          工作中的倾向: "主动承担高难度任务；设定并达成具有挑战性的目标；推动团队追求卓越"
        组织意识:
          潜质特点: "深刻理解组织运作机制和战略方向。具备全局思维和战略眼光"
          工作中的倾向: "从组织角度思考问题；主动推动战略落地；在跨部门协作中发挥桥梁作用"

    medium:
      dimension_eval: "具备基础管理动力但深度不足。在熟悉领域展现领导意愿，但面对挑战时存在犹豫；成就动机受外部激励影响较大；组织理解停留在部门层面。"
      sub_dimensions:
        领导意愿:
          潜质特点: "在熟悉领域愿意承担领导角色，但面对新挑战时存在顾虑"
          工作中的倾向: "在熟悉团队中发挥领导作用；面对新项目时需要鼓励；领导风格相对保守"
        追求成就:
          潜质特点: "在明确目标下追求成就，但自主设定高目标的能力不足"
          工作中的倾向: "完成既定目标表现良好；较少主动设定挑战性目标；成就动机受外部认可影响"
        组织意识:
          潜质特点: "理解部门运作机制，但全局视角有限"
          工作中的倾向: "在部门内协作良好；跨部门协作需要指导；较少主动关注组织战略"

    low:
      dimension_eval: "管理动力薄弱，领导意愿不明确。倾向于专业岗位发展，对管理责任存在回避；成就动机主要来自个人专业发展；组织意识局限在个人工作范围。"
      sub_dimensions:
        领导意愿:
          潜质特点: "对领导角色缺乏兴趣，倾向于专业发展路径"
          工作中的倾向: "拒绝承担团队领导责任；专注于个人专业能力提升；较少参与管理决策"
        追求成就:
          潜质特点: "成就动机主要来自专业领域，对管理成就缺乏兴趣"
          工作中的倾向: "在专业领域追求卓越；对管理相关成就缺乏动力；较少关注团队整体绩效"
        组织意识:
          潜质特点: "组织意识局限在个人工作范围，缺乏全局思维"
          工作中的倾向: "专注于个人工作任务；较少关注组织整体运作；跨部门协作主动性不足"

    bad:
      dimension_eval: "管理动力薄弱，领导意愿不明确。倾向于专业岗位发展，对管理责任存在回避；成就动机主要来自个人专业发展；组织意识局限在个人工作范围。"
      sub_dimensions:
        领导意愿:
          潜质特点: "对领导角色缺乏兴趣，倾向于专业发展路径"
          工作中的倾向: "拒绝承担团队领导责任；专注于个人专业能力提升；较少参与管理决策"
        追求成就:
          潜质特点: "成就动机主要来自专业领域，对管理成就缺乏兴趣"
          工作中的倾向: "在专业领域追求卓越；对管理相关成就缺乏动力；较少关注团队整体绩效"
        组织意识:
          潜质特点: "组织意识局限在个人工作范围，缺乏全局思维"
          工作中的倾向: "专注于个人工作任务；较少关注组织整体运作；跨部门协作主动性不足"

  管理他人:
    high:
      dimension_eval: "具备卓越的人际影响艺术，精准把握团队情感脉搏。能深度解读非语言信号，自然融入他人视角决策，系统化培养人才梯队，构建高信任度团队生态。"
      sub_dimensions:
        人际洞察:
          潜质特点: "敏锐捕捉微表情、语气变化等非语言信号，精准判断未言明的核心诉求。能预判人际关系发展轨迹，识别潜在合作与冲突点"
          工作中的倾向: "会议中实时观察多方反应调整沟通策略；预判利益相关方潜在顾虑；提前化解团队摩擦"
        同理心:
          潜质特点: "达成情感共振与认知融合的深度理解，能还原他人决策逻辑。在保持自我立场同时内化多元视角"
          工作中的倾向: "冲突调解时展现多立场整合能力；跨部门协作中主动设计共赢方案；制度设计融入人性化考量"
        发挥他人:
          潜质特点: "建立人才赋能系统，精准匹配发展机会与个人特质。将他人成功视为组织资本增值"
          工作中的倾向: "系统性实施岗位轮换计划；创建个性化发展路径图；主动让渡关键机会培养继任者"

    medium:
      dimension_eval: "具备基础人际理解能力但深度不足。能识别显性情绪信号但忽略潜在动机，在熟悉情境中展现同理心，人才开发聚焦任务需求而非长远发展。"
      sub_dimensions:
        人际洞察:
          潜质特点: "能捕捉明显情绪变化但解读存在时滞。对常规行为模式有认知，非常规信号易误判"
          工作中的倾向: "日常沟通能感知对方情绪基调；复杂会议需要事后复盘才能理解潜台词；偶有过度解读中性表达"
        同理心:
          潜质特点: "在相似背景同事间展现理解，差异较大时出现认知盲区。情感共鸣强于立场融合"
          工作中的倾向: "能理解部门内部诉求但跨职能协作困难；可执行标准化安抚流程；难以协调深层价值观冲突"
        发挥他人:
          潜质特点: "基于任务需求分配机会，培养动作呈现碎片化。关注即战力多于潜能开发"
          工作中的倾向: "按能力匹配当前任务；提供基础指导但缺发展体系；人才推荐依赖显性业绩数据"

    low:
      dimension_eval: "人际理解存在显著障碍，常误判他人意图。决策过度自我中心化，人员管理侧重事务分配忽视成长赋能。"
      sub_dimensions:
        人际洞察:
          潜质特点: "对非语言信号感知迟钝，常将社交礼仪误解为真实态度。行为归因存在刻板印象"
          工作中的倾向: "忽略会议中的反对信号；将沉默误认为认同；对离职征兆反应滞后"
        同理心:
          潜质特点: "情感理解存在认知屏障，常将不同立场视为对抗。归因时过度强调个人责任"
          工作中的倾向: "坚持己见导致决策僵局；跨文化沟通频发摩擦；制度执行缺乏弹性空间"
        发挥他人:
          潜质特点: "视团队成员为执行工具，发展投入视为资源消耗。机会分配倾向控制而非赋能"
          工作中的倾向: "任务分配忽略个体差异；重要机会集中亲信；反馈聚焦差错而非成长"

    bad:
      dimension_eval: "人际理解存在显著障碍，常误判他人意图。决策过度自我中心化，人员管理侧重事务分配忽视成长赋能。"
      sub_dimensions:
        人际洞察:
          潜质特点: "对非语言信号感知迟钝，常将社交礼仪误解为真实态度。行为归因存在刻板印象"
          工作中的倾向: "忽略会议中的反对信号；将沉默误认为认同；对离职征兆反应滞后"
        同理心:
          潜质特点: "情感理解存在认知屏障，常将不同立场视为对抗。归因时过度强调个人责任"
          工作中的倾向: "坚持己见导致决策僵局；跨文化沟通频发摩擦；制度执行缺乏弹性空间"
        发挥他人:
          潜质特点: "视团队成员为执行工具，发展投入视为资源消耗。机会分配倾向控制而非赋能"
          工作中的倾向: "任务分配忽略个体差异；重要机会集中亲信；反馈聚焦差错而非成长"

  管理事务:
    high:
      dimension_eval: "具备战略级事务处理架构能力，在高度复杂情境中展现卓越的问题破解艺术。能构建多维联结框架洞察系统关联，将抽象概念转化为可执行方案，主动引领组织变革进程。"
      sub_dimensions:
        跨领域思考:
          潜质特点: "形成全域知识熔断机制，在迥异领域间建立高价值关联。将跨界信息转化为创新杠杆，识别隐性系统连接点"
          工作中的倾向: "主持跨部门项目时创造技术-市场-供应链三元模型；用生物系统原理优化生产流程；构建行业交叉创新智库"
        概念性思维:
          潜质特点: "发展多维抽象建模能力，实现九层问题解构与重构。精准剥离非本质要素，核心变量控制精度达95%以上"
          工作中的倾向: "将百万级用户数据抽象为三阶增长引擎；用物理场论设计组织协作网络；复杂决策时实施五级过滤机制"
        适应变化情境:
          潜质特点: "将变革转化为组织进化动能，构建预见性适应体系。在VUCA环境中创造稳定输出范式，实现反脆弱成长"
          工作中的倾向: "主动实施三个月组织架构迭代周期；创建变革收益可视化仪表盘；设计压力测试沙盘演练机制"

    medium:
      dimension_eval: "具备常规事务处理能力但系统性不足。能应对标准化复杂场景，全局视角存在局部盲区；概念提炼停留在现象层级，适应性表现为被动调整而非主动进化。"
      sub_dimensions:
        跨领域思考:
          潜质特点: "在关联领域能建立基础连接，但价值转化效率有限。跨界思维依赖外部触发，创新关联存在随机性"
          工作中的倾向: "可完成跨部门协作基础流程；需要框架模板引导联想；创新方案常停留在概念层难以落地"
        概念性思维:
          潜质特点: "对中度复杂问题具备解构能力，核心变量识别准确率70%左右。归因分析存在表层化倾向，方法论移植能力弱"
          工作中的倾向: "能梳理基础业务流程框架；需要多次迭代才能确定关键要素；面对全新问题类型需外部支持"
        适应变化情境:
          潜质特点: "适应过程伴随效能波动，变革初期存在本能抗拒。调整周期与变化强度正相关，需明确收益引导"
          工作中的倾向: "组织调整后需1-2月恢复期；政策变更时出现短期效能下降；能在指导下建立新工作模式"

    low:
      dimension_eval: "事务处理能力局限在单一线性维度。面临复杂信息时出现认知超载，决策依赖经验复制而非本质洞察，变革适应性存在系统性障碍。"
      sub_dimensions:
        跨领域思考:
          潜质特点: "认知边界锁定在专业孤岛，跨域信息视为干扰噪声。关联尝试引发认知混乱，创新路径依赖机械复制"
          工作中的倾向: "拒绝参与跨职能项目；用本部门标准解决全域问题；创新会议中坚持原有方案"
        概念性思维:
          潜质特点: "陷入细节沼泽无法抽离，现象与本质混淆严重。复杂信息触发决策瘫痪，关键因子识别率低于40%"
          工作中的倾向: "百页报告无法提炼三要点；新问题直接套用旧方案；分析会议纠缠非核心细节"
        适应变化情境:
          潜质特点: "变革触发防御性行为模式，将调整视为能力否定。适应周期远超合理范围，隐性抵制行为持续存在"
          工作中的倾向: "组织调整后三个月仍抵触新流程；政策变更时传播消极预期；关键系统升级时坚持传统操作"

    bad:
      dimension_eval: "事务处理能力局限在单一线性维度。面临复杂信息时出现认知超载，决策依赖经验复制而非本质洞察，变革适应性存在系统性障碍。"
      sub_dimensions:
        跨领域思考:
          潜质特点: "认知边界锁定在专业孤岛，跨域信息视为干扰噪声。关联尝试引发认知混乱，创新路径依赖机械复制"
          工作中的倾向: "拒绝参与跨职能项目；用本部门标准解决全域问题；创新会议中坚持原有方案"
        概念性思维:
          潜质特点: "陷入细节沼泽无法抽离，现象与本质混淆严重。复杂信息触发决策瘫痪，关键因子识别率低于40%"
          工作中的倾向: "百页报告无法提炼三要点；新问题直接套用旧方案；分析会议纠缠非核心细节"
        适应变化情境:
          潜质特点: "变革触发防御性行为模式，将调整视为能力否定。适应周期远超合理范围，隐性抵制行为持续存在"
          工作中的倾向: "组织调整后三个月仍抵触新流程；政策变更时传播消极预期；关键系统升级时坚持传统操作"

# 报告模板配置
template:
  name: "management_potential_template.html"
  title: "管理潜质测评报告"
  description: "本报告基于管理潜质测评结果生成，反映受测者在管理序列上的发展潜力和能力特点。"

# 雷达图配置
radar_chart:
  title: "管理潜质雷达图"
  subtitle: "四大维度能力分布"
  max_score: 10
  min_score: 0
  grid_lines: [0, 2, 4, 6, 8, 10]
  background_colors:
    - "#00CC0020"  # 自我成长与发展
    - "#9900FF20"  # 管理动力
    - "#FF333320"  # 管理他人
    - "#0066FF20"  # 管理事务

# 报告生成配置
report_generation:
  output_format: "pdf"
  include_chart: true
  include_summary: true
  include_recommendations: true
  language: "zh-CN" 