# 商业推理能力测评配置文件

paper_id: 21

paper_name: "商业推理能力测评"

paper_description: "商业推理能力是指个体在复杂商业环境中，运用逻辑思维、数据分析、战略判断等能力，解决商业问题并做出有效决策的综合能力。"

paper_version: "v1.0"



# 数据字段映射（Excel列名到内部字段名的映射）

field_mapping:

  姓名: "name"

  总分: "total_score"

  大维度1：复杂信息理解: "复杂信息理解"

  大维度2：批判性评估: "批判性评估"

  大维度3：策略性推理: "策略性推理"

  大维度4：概念性推理: "概念性推理"



# 维度结构定义

dimensions:

  - name: "复杂信息理解"

    color: "#4CAF50"

    description: "指洞察文字、图表等资料的能力，反映能否快速抓住复杂信息中的要点、提取出关键信息。"

    radar_angles: [0]

    sub_dimensions:

      - name: "信息提取"

        description: "从复杂资料中提取关键信息的能力"





  - name: "批判性评估"

    color: "#2196F3"

    description: "思维的严谨性，指批判性质疑的能力，反映能否敏锐地发现隐含的逻辑漏洞、缺陷或问题。"

    radar_angles: [90]

    sub_dimensions:

      - name: "逻辑分析"

        description: "识别逻辑错误和论证漏洞的能力"





  - name: "策略性推理"

    color: "#FF9800"

    description: "思维的策略性，指从多角度分析问题原因的能力，反映能否灵活地转换思路，挖掘出问题解决的关键线索。"

    radar_angles: [180]

    sub_dimensions:

      - name: "多角度思考"

        description: "从不同角度分析问题的能力"





  - name: "概念性推理"

    color: "#9C27B0"

    description: "思维的归纳性，指从具体事物中归纳出通用规律的能力，反映能否跳出具体信息，做到举一反三。"

    radar_angles: [270]

    sub_dimensions:

      - name: "归纳总结"

        description: "从具体事例中提炼普遍规律的能力"





# 分数区间定义

score_levels:

  - name: "卓越水平"

    min: 8.5

    max: 10.0

    summary: "展现出卓越的商业推理能力，在复杂商业环境中能够快速识别关键问题，运用多种推理方法得出准确结论，具备战略级商业洞察力。"

    development_focus: "重点培养战略领导力和跨领域整合能力，同时防范过度分析导致的决策延迟"

    color: "#4CAF50"



  - name: "优秀水平"

    min: 7.5

    max: 8.4

    summary: "具备扎实的商业推理基础，能够有效处理常规商业问题，在熟悉领域表现出色，具备良好的分析思维和判断能力。"

    development_focus: "拓展分析维度，提升复杂情境下的推理能力"

    color: "#FFC107"



  - name: "良好水平"

    min: 6.5

    max: 7.4

    summary: "具备基础商业推理能力，能够处理标准化的商业问题，在指导下能够完成分析任务，需要进一步提升独立分析能力。"

    development_focus: "加强逻辑思维训练，提升数据分析能力"

    color: "#2196F3"



  - name: "基础水平"

    min: 1.0

    max: 6.4

    summary: "商业推理能力基础薄弱，需要系统化训练和大量实践。建议通过专项培训提升逻辑思维和商业分析能力。"

    development_focus: "建议参加商业分析培训，提升基础推理能力"

    color: "#F44336"



# 维度评价内容

dimension_evaluations:

  复杂信息理解:

    high:

      dimension_eval: "能够在短时间内从大量复杂信息中提取关键要点,能够准确理解信息的深层含义和潜在联系,能够识别信息中的关键假设和前提条件。"

      



    medium:

      dimension_eval: "能较好地理解复杂信息的核心内容,能够识别信息中的关键细节和要点,对信息的整体把握较好。"

      



    low:

      dimension_eval: "能够理解信息的表面含义，但对深层联系把握不足,信息提取速度一般，有时会遗漏重要细节,对复杂信息的处理需要更多时间和精力。"

      



    bad:

      dimension_eval: "理解复杂信息的能力相对不足,容易遗漏信息中的重要细节和要点,面对复杂信息时容易产生困惑或误解。"

      



  数据分析:

    high:

      dimension_eval: "具备卓越的数据分析能力，能够从复杂数据中提取关键洞察，运用多种分析方法解决商业问题。"





    medium:

      dimension_eval: "具备良好的数据分析基础，能够处理常规数据分析任务，但在复杂分析中需要指导。"





    low:

      dimension_eval: "数据分析能力基础薄弱，在复杂数据分析中容易出现错误，需要系统化训练。"





    bad:

      dimension_eval: "数据分析能力严重不足，在数据分析中经常出现错误，需要基础训练。"





  战略思维:

    high:

      dimension_eval: "具备卓越的战略思维能力，能够从全局和长远角度思考问题，制定有效的战略规划。"





    medium:

      dimension_eval: "具备良好的战略思维基础，能够在熟悉领域制定有效策略，但在复杂情境下需要指导。"





    low:

      dimension_eval: "战略思维能力基础薄弱，在复杂战略问题中容易出现短视，需要系统化训练。"





    bad:

      dimension_eval: "战略思维能力严重不足，在战略问题中经常出现短视和错误判断，需要基础训练。"





  商业洞察:

    high:

      dimension_eval: "具备卓越的商业洞察能力，能够敏锐感知市场变化，准确把握商业机会，创造显著价值。"





    medium:

      dimension_eval: "具备良好的商业洞察基础，能够在熟悉领域把握商业机会，但在复杂环境中需要指导。"





    low:

      dimension_eval: "商业洞察能力基础薄弱，在复杂商业环境中容易出现判断错误，需要系统化训练。"





    bad:

      dimension_eval: "商业洞察能力严重不足，在商业环境中经常出现判断错误，需要基础训练。"

      sub_dimensions:

        市场敏感:

          潜质特点: "市场敏感度严重不足，无法感知市场变化"

          工作中的倾向: "无法感知市场变化；经常错过市场机会；缺乏市场敏感度"

        竞争分析:

          潜质特点: "竞争分析能力严重不足，无法进行有效竞争分析"

          工作中的倾向: "无法进行竞争分析；竞争策略错误；缺乏竞争意识"

        价值创造:

          潜质特点: "价值创造能力严重不足，无法发现和创造价值"

          工作中的倾向: "无法发现价值机会；无法创造商业价值；缺乏价值意识"



# 报告模板配置

template:

  name: "business_reasoning_template.html"

  title: "商业推理能力测评报告"

  description: "本报告基于商业推理能力测评结果生成，反映受测者在商业推理和决策方面的能力特点。"



# 雷达图配置

radar_chart:

  title: "商业推理能力雷达图"

  subtitle: "四大维度能力分布"

  max_score: 10

  min_score: 0

  grid_lines: [0, 2, 4, 6, 8, 10]

  background_colors:

    - "#4CAF5020"  # 逻辑推理

    - "#2196F320"  # 数据分析

    - "#FF980020"  # 战略思维

    - "#9C27B020"  # 商业洞察



# 报告生成配置

report_generation:

  output_format: "pdf"

  include_chart: true

  include_summary: true

  include_recommendations: true

  language: "zh-CN" 